### ISSUE TITLE
PlayerPool GetClosest and GetClosestOnSide incorrect behaviour

### ISSUE THREAD

**Issue by DodoBirby** [Lojemiru/Another-Mediocre-2D-Engine#14] opened 2023-07-17 02:10 UTC
The GetClosest function uses an incorrect algorithm to calculate the closest player.
Situation:
2 players at equivalent y coordinates, but 1 player is closer on the x coordinate.
Expected result:
Player who is closer on x coordinate gets chosen.
Actual Result:
Arbitrary based on which player is first in the pool.

GetClosestOnSide seems to not take into account y coordinates for left and right sides, and doesn't take into account x coordinates for up and down sides but depending on their intended use case this might not be a bug.

**Comment by Lojemiru** [comment] 2023-08-05 23:29
Definitely unintended behavior. Reviewing the methods, the code I wrote for these is exceptionally dumb... should be fixed now, pushing shortly. Thanks for the report!

**Closed as completed** 2023-08-05 23:30 UTC
